name: AoC19-Haskell
version: 0.1.0.0
github: "Riddarvid/AoC19-Haskell"
license: BSD3
author: "Riddarvid"
maintainer: "code@arvid-rydberg.se"
copyright: "2023 Riddarvid"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Riddarvid/AoC19-Haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6.5.1
  - unordered-containers >= 0.2.19.1
  - mtl >= 2.2.2
  - parsec >= 3.1.15.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  AoC19-Haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - AoC19-Haskell

tests:
  AoC19-Haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - AoC19-Haskell
